name: CI

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    Check:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3

            - name: Setup
              run: |
                  sudo apt-get update
                  sudo apt install -y curl

                  # remove pre-installed packages
                  sudo apt remove npm nodejs

                  # Install Node.js 16.x from upstream b/c polkadot/jest can't work withh old versions
                  curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

                  sudo apt-get install -y nodejs
                  sudo npm install -g yarn
            - name: Install deps
              run: yarn install
            - name: Typecheck
              run: yarn typecheck
            - name: Lint
              run: yarn lint
    Formatting:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Setup
              run: |
                  sudo apt-get update
                  sudo apt install -y curl

                  # remove pre-installed packages
                  sudo apt remove npm nodejs

                  # Install Node.js 16.x from upstream b/c polkadot/jest can't work withh old versions
                  curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

                  sudo apt-get install -y nodejs
                  sudo npm install -g yarn
            - name: Install deps
              run: yarn install
            - name: Check formatting
              run: yarn format -c
